# Use the official Python image from Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the tar archive into the container
COPY web/dist/app.tar /app/app.tar

# Extract the contents of the tar file
RUN tar -xvf /app/app.tar -C /app

# Install Flask inside the container
RUN pip install --no-cache-dir Flask matplotlib

# Expose port 5000 for the Flask app
EXPOSE 5122

# Command to run the Flask app
CMD ["python", "random_numbers_api.py"]
